version: '3'

volumes:
 repo:
 portainer_data:

services:
 site:
  image: valterruas/ivar_site
  hostname: ivar
  container_name: ivarsite
  ports:
   - 8085:80
  volumes:
   - repo:/usr/local/apache2/htdocs
   - /srv/backup:/data

 monitoracao:
  image: google/cadvisor
  ports:
   - 8585:8080
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:ro
    - /sys:/sys:ro
    - /var/lib/docker:/var/lib/docker:ro
    - /dev/disk:/dev/disk:ro

 portainer:
  image: portainer/portainer
  ports:
   - 9001:9000
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
   - portainer_data:/data

 reverse-proxy:
  image: traefik
  command:
   - "--api"
   - "--docker"
   - "--web"
  ports:
   - 80:80
   - 8080:8080
