FROM debian
RUN apt-get update && apt-get install apache2 -y
RUN apt-get clean all
RUN mkdir /var/run/apache2
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_RUN_DIR /var/run/apache2
ENV APACHE_LOCK_DIR /var/lock/apache2
ENV APACHE_LOG_DIR /var/log/apache2
COPY index.html /var/www/html/
CMD /usr/sbin/apache2 -DFOREGROUND
